### ISSUE TITLE
Any update on merged dataset...?

### ISSUE THREAD

**Issue by MukulKadaskar** [WinnieLaugh/Dataset_Merger#1]
Will you be adding the link to the merged dataset...?

**Comment by WinnieLaugh** [comment]
Hi @MukulKadaskar ,

The link to the merged dataset and the description to use it can be found on the project homepage:

https://w-h-zhang.github.io/projects/dataset_merging/dataset_merging.html

Thanks.

Best,
Wenhua

**Comment by MukulKadaskar** [comment]
What is the visualize.tar file for?

**Comment by MukulKadaskar** [comment]
It only has the output results, whereas I am talking about the re-organized and uniform data to be used as input for the algorithm.

**Comment by WinnieLaugh** [comment]
I was told that I am not allowed to publish the re-organized datasets due to the license problems, but thank you for this reminder, I will release the code I used to process these data into the uniform format recently.

**Comment by MukulKadaskar** [comment]
Can you share the links to those files..?

**Comment by WinnieLaugh** [comment]
Sure. 

panNuke: https://jgamper.github.io/PanNukeDataset/
CoNSeP: https://warwick.ac.uk/fac/cross_fac/tia/data/hovernet/
NuCLS: https://sites.google.com/view/nucls/home
MoNuSAC: https://monusac-2020.grand-challenge.org/Home/

**Comment by MukulKadaskar** [comment]
Are there any scripts to convert them to a same format or they have to fed as it is..?

**Comment by WinnieLaugh** [comment]
Sorry about the late reply! I was busy on another project recently. 

I will try my best to release the scripts to convert them within this week. Thank you very much for this suggestion!

**Comment by WinnieLaugh** [comment]
Hi, I have uploaded the required scripts. They should be able to convert the downloaded datasets into the same format.

**Comment by MukulKadaskar** [comment]
What are the .txt files during sparse_training, as they are not created during the dataset preparation?

**Comment by WinnieLaugh** [comment]
It is the files to indicate the different nuclei seperating traing/valid/test splits, I have updated the script to create this file too. Thanks a lot for your reminder.
