### ISSUE TITLE
Getting the "ours" labels

### ISSUE THREAD

**Issue by mortunco** [WinnieLaugh/Dataset_Merger#2]
Hello,

Thank you for coming up such a tool to standardize "almost" arbitrary labels in different datasets.

Is there a way that I could get "ours" labels across all datasets? I apologise if this already shared and very obvious.

Best regards,

T.

**Comment by WinnieLaugh** [comment]
Hi,

Thank you very much for your interest in our work! : )

You can find the related information on the inferred labels in the [project website](https://w-h-zhang.github.io/projects/dataset_merging/dataset_merging.html).
